<!--
  Diverging bar chart: land use (m²/kg) extends leftward, freshwater (L/kg)
  extends rightward, food name centered between them. Each side has its own
  scale. Same plant/animal coloring as the rest of the piece; legume rows
  highlighted on a linen band that spans both sides.

  Data: /data/landuse-water.csv (generated by scripts/extract_landuse_water.py
  from data/landuse-emissions.xls "Results - Retail Weight").
-->
<script>
  import { onMount } from 'svelte';
  import * as d3 from 'd3';
  import { legumeColors, chart as chartTokens } from '../palette.js';
  import csvRaw from '../data/landuse-water.csv?raw';

  let svgEl = $state();
  let wrapEl = $state();
  let width = $state(900);
  let height = $state(560);
  let rows = $state([]);

  onMount(() => {
    rows = d3.csvParse(csvRaw, (d) => ({
      product: d.product,
      kind: d.kind, // 'animal' | 'plant' | 'plant-legume'
      land: +d.land_use_m2,
      water: +d.freshwater_l,
    }));

    const ro = new ResizeObserver((entries) => {
      const r = entries[0].contentRect;
      width = r.width;
      height = Math.max(460, Math.min(620, r.width * 0.7));
      draw();
    });
    ro.observe(wrapEl);
    draw();
    return () => ro.disconnect();
  });

  $effect(() => {
    rows;
    width;
    height;
    draw();
  });

  function draw() {
    if (!svgEl || rows.length === 0) return;

    const svg = d3.select(svgEl);
    svg.selectAll('*').remove();

    const colors = legumeColors();
    const tokens = chartTokens();

    // On narrow screens the two side scales get so short that the bottom
    // axis tick labels visually merge. Drop the axes there and move the
    // unit labels up under the side headers instead.
    const isMobile = width < 560;
    const fitW = (sel, maxW) => {
      if (maxW > 0 && sel.node().getComputedTextLength() > maxW) {
        sel.attr('textLength', maxW).attr('lengthAdjust', 'spacingAndGlyphs');
      }
    };

    const sorted = [...rows].sort((a, b) => d3.descending(a.land, b.land));
    const isAnimal = (d) => d.kind === 'animal';
    const colorFor = (d) => (isAnimal(d) ? colors.kidney : colors.duPuy);

    const margin = { top: 56, right: 56, bottom: 48, left: 56 };
    const centerW = 150;
    const w = Math.max(0, width - margin.left - margin.right);
    const h = Math.max(0, height - margin.top - margin.bottom);
    const sideW = Math.max(0, (w - centerW) / 2);

    const y = d3
      .scaleBand()
      .domain(sorted.map((d) => d.product))
      .range([0, h])
      .padding(0.32);

    // Scales: range [0, sideW] — used for bar widths. Axes get a reversed
    // copy when needed so 0 sits at the inside edge (touching the center).
    const xLand = d3
      .scaleLinear()
      .domain([0, d3.max(sorted, (d) => d.land) * 1.05])
      .range([0, sideW]);

    const xWater = d3
      .scaleLinear()
      .domain([0, d3.max(sorted, (d) => d.water) * 1.05])
      .range([0, sideW]);

    const g = svg
      .attr('viewBox', `0 0 ${width} ${height}`)
      .append('g')
      .attr('transform', `translate(${margin.left},${margin.top})`);

    // side headers
    const headerY = -28;
    const luHeaderX = sideW - 12;
    const luHeader = g
      .append('text')
      .attr('x', luHeaderX)
      .attr('y', headerY)
      .attr('text-anchor', 'end')
      .attr('fill', 'var(--text-on-light)')
      .style('font-family', 'var(--sans)')
      .style('font-size', '11px')
      .style('font-weight', '700')
      .style('letter-spacing', '0.1em')
      .style('text-transform', 'uppercase')
      .text('← Land use');
    const fwHeaderX = sideW + centerW + 12;
    const fwHeader = g
      .append('text')
      .attr('x', fwHeaderX)
      .attr('y', headerY)
      .attr('fill', 'var(--text-on-light)')
      .style('font-family', 'var(--sans)')
      .style('font-size', '11px')
      .style('font-weight', '700')
      .style('letter-spacing', '0.1em')
      .style('text-transform', 'uppercase')
      .text('Freshwater →');
    // Squish each header to fit if it would run past its viewBox edge on
    // narrow screens instead of being clipped. In this group's coordinate
    // space the viewBox spans [-margin.left, width - margin.left]; the
    // land header is end-anchored (grows left), the water header start-
    // anchored (grows right).
    const luMaxW = luHeaderX - -margin.left - 4;
    const fwMaxW = width - margin.left - fwHeaderX - 4;
    fitW(luHeader, luMaxW);
    fitW(fwHeader, fwMaxW);

    // On mobile, the unit lives under its side header (bottom axis dropped).
    if (isMobile) {
      const luUnit = g
        .append('text')
        .attr('x', luHeaderX)
        .attr('y', headerY + 15)
        .attr('text-anchor', 'end')
        .attr('fill', tokens.axis)
        .style('font-family', 'var(--sans)')
        .style('font-size', '10px')
        .text('m² per kg of food');
      const fwUnit = g
        .append('text')
        .attr('x', fwHeaderX)
        .attr('y', headerY + 15)
        .attr('fill', tokens.axis)
        .style('font-family', 'var(--sans)')
        .style('font-size', '10px')
        .text('litres per kg of food');
      fitW(luUnit, luMaxW);
      fitW(fwUnit, fwMaxW);
    }

    // food labels in center column
    g.selectAll('text.food')
      .data(sorted)
      .join('text')
      .attr('class', 'food')
      .attr('x', sideW + centerW / 2)
      .attr('y', (d) => y(d.product) + y.bandwidth() / 2)
      .attr('text-anchor', 'middle')
      .attr('dominant-baseline', 'middle')
      .attr('fill', 'var(--text-on-light)')
      .style('font-family', 'var(--sans)')
      .style('font-size', '13px')
      .style('font-weight', '500')
      .text((d) => d.product);

    // land bars — extend leftward from the center column's left edge
    g.selectAll('rect.land')
      .data(sorted)
      .join('rect')
      .attr('class', 'land')
      .attr('x', (d) => sideW - xLand(d.land))
      .attr('y', (d) => y(d.product))
      .attr('width', (d) => xLand(d.land))
      .attr('height', y.bandwidth())
      .attr('fill', colorFor)
      .attr('rx', 2);

    // water bars — extend rightward from the center column's right edge
    g.selectAll('rect.water')
      .data(sorted)
      .join('rect')
      .attr('class', 'water')
      .attr('x', sideW + centerW)
      .attr('y', (d) => y(d.product))
      .attr('width', (d) => xWater(d.water))
      .attr('height', y.bandwidth())
      .attr('fill', colorFor)
      .attr('rx', 2);

    // value labels — outside each bar end
    g.selectAll('text.land-val')
      .data(sorted)
      .join('text')
      .attr('class', 'land-val')
      .attr('x', (d) => sideW - xLand(d.land) - 6)
      .attr('y', (d) => y(d.product) + y.bandwidth() / 2)
      .attr('text-anchor', 'end')
      .attr('dominant-baseline', 'middle')
      .attr('fill', colorFor)
      .style('font-family', 'var(--sans)')
      .style('font-size', '11px')
      .style('font-weight', '600')
      .text((d) =>
        d.land < 10 ? d.land.toFixed(1) : `${Math.round(d.land)}`,
      );

    g.selectAll('text.water-val')
      .data(sorted)
      .join('text')
      .attr('class', 'water-val')
      .attr('x', (d) => sideW + centerW + xWater(d.water) + 6)
      .attr('y', (d) => y(d.product) + y.bandwidth() / 2)
      .attr('dominant-baseline', 'middle')
      .attr('fill', colorFor)
      .style('font-family', 'var(--sans)')
      .style('font-size', '11px')
      .style('font-weight', '600')
      .text((d) =>
        d.water < 1000
          ? `${Math.round(d.water)}`
          : `${(d.water / 1000).toFixed(1)}k`,
      );

    if (!isMobile) {
    // axes — land reversed so 0 sits at the inside edge
    const xLandAxis = xLand.copy().range([sideW, 0]);
    g.append('g')
      .attr('transform', `translate(0,${h})`)
      .call(d3.axisBottom(xLandAxis).ticks(4))
      .call((sel) => sel.select('.domain').remove())
      .call((sel) => sel.selectAll('line').attr('stroke', tokens.grid))
      .call((sel) =>
        sel
          .selectAll('text')
          .attr('fill', tokens.axis)
          .style('font-family', 'var(--sans)')
          .style('font-size', '11px'),
      );

    g.append('g')
      .attr('transform', `translate(${sideW + centerW},${h})`)
      .call(
        d3
          .axisBottom(xWater)
          .ticks(4)
          .tickFormat((v) => (v < 1000 ? v : `${v / 1000}k`)),
      )
      .call((sel) => sel.select('.domain').remove())
      .call((sel) => sel.selectAll('line').attr('stroke', tokens.grid))
      .call((sel) =>
        sel
          .selectAll('text')
          .attr('fill', tokens.axis)
          .style('font-family', 'var(--sans)')
          .style('font-size', '11px'),
      );

    // axis unit labels
    g.append('text')
      .attr('x', sideW / 2)
      .attr('y', h + 38)
      .attr('text-anchor', 'middle')
      .attr('fill', tokens.axis)
      .style('font-family', 'var(--sans)')
      .style('font-size', '11px')
      .text('m² per kg of food');

    g.append('text')
      .attr('x', sideW + centerW + sideW / 2)
      .attr('y', h + 38)
      .attr('text-anchor', 'middle')
      .attr('fill', tokens.axis)
      .style('font-family', 'var(--sans)')
      .style('font-size', '11px')
      .text('litres per kg of food');
    }
  }
</script>

<figure class="chart" bind:this={wrapEl}>
  <figcaption class="cap">
    <span class="subtitle">Land use and freshwater withdrawals per kilogram of food</span>
    <span class="title">Beef and cheese tower above legumes on land use</span>
  </figcaption>
  <svg bind:this={svgEl}></svg>
  <p class="source">
    Source:
    <a
      href="https://www.science.org/doi/10.1126/science.aaq0216"
      target="_blank"
      rel="noopener"
    >Poore &amp; Nemecek (2018)</a>, supplementary data, retail-weight functional
    unit · mean of all studies per product.
  </p>
</figure>

<style>
  .chart {
    width: 100%;
    margin: 0;
  }
  svg {
    width: 100%;
    height: auto;
    display: block;
  }
  /* caption styles inherited from .chart .cap rules in app.css */
</style>
